apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    type: frontened
    app: nginx
spec:
  type: ClusterIP
  selector:
    type: frontened
    app: nginx
  ports:
  - port: 9001
    targetPort: 80
