apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node
  labels:
    app: node-v1
spec:
  replicas: 2
  minReadySeconds: 5 #To check if the server is ready
  selector:
    matchLabels:
      app: node-v1
  template:  
      metadata:
        labels:
          app: node-v1
      spec: 
        containers:
        - name: my-node
          image: arpitgoyal1982/node-srv:v2
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"